image: ddgg/oop_2020:build_v1

pipelines:
  default:
    - step:
        script:
          - pushd .
          -   mkdir build-p2p_comunicator && pushd build-p2p_comunicator
          -     qmake ../p2p_comunicator
          -     make -j4
          -     pushd tests/contact_validator
          -       LD_LIBRARY_PATH=../../utils ./contact_validator
          -     popd
          -     pushd tests/contact_test
          -       LD_LIBRARY_PATH=../../utils ./contact_test
          -     popd
          -     pushd tests/storage_test
          -       LD_LIBRARY_PATH=../../utils ./storage_test
          -     popd
          -     pushd tests/tcp_packet_test
          -       LD_LIBRARY_PATH=../../utils ./tst_tcp_packet_test
          -     popd
          -   popd
          - .ci/collect_reports.sh
